### ISSUE TITLE
Getting 404 errors when opening logs with embedded images

### ISSUE THREAD

**Issue by UrbanBobek** [Olog/phoebus-olog-web-client#100]
Hi all,

I tried deploying the phoebus-olog web client, and while I am able see and create logs, I get 404 error when trying to view logs with embedded images.

First I tried configuring it with our phoebus-OLog service, but I can reproduce the error using the provided docker containers. Here are the steps I took:
1. Built the app using the provided command `REACT_APP_BASE_URL=Olog/ npm run-script build`
2. Created a directory `/var/www/olog-web` and pasted the contents of the `build` directory there
3. Ran `docker compose up` to start olog, mongo and elasticsearch
4. Created an apache configuration file:
 - I used the example configuration file from the README as an example, but I had to add the `DocumentRoot` option for apache to serve the build artifacts
 ```
 <VirtualHost *:80>
   ProxyPreserveHost On
   DocumentRoot /var/www/olog-web
   ServerName localhost
   ProxyPass /Olog/ http://localhost:8080/Olog/
   ProxyPassReverse /Olog/ http://localhost:8080/Olog/

   <Directory "/var/www/olog-web/">
      RewriteEngine on
      RewriteCond %{HTTP_ACCEPT} text/html
      RewriteCond %{REQUEST_FILENAME} !-f
      RewriteRule ^ index.html [last]
      RewriteRule ^ - [last]
   </Directory>
</VirtualHost>
 ```
5. Enabled the site and restarted apache. 

When connecting to `localhost` everything seems to work. But if I try to open a log that contains an embedded image, I get a `404 Not Found` error.
![image](https://github.com/Olog/phoebus-olog-web-client/assets/43409317/91b1f578-4cd7-4311-afec-ace9da5af15b)

Looking at the apache access log, I get the following output when opening a log with an embedded image
```
localhost:80 127.0.0.1 - - [07/Jun/2023:18:31:09 +0200] "GET /logs/Olog//attachment/9c9c969e-6e39-4eb9-a206-40cbef04b152 HTTP/1.1" 404 487 "http://localhost/logs/8" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0"
```
If an image is not embedded but only attached, I do not get the error, but I cannot see the image when clicking on the attachment.
\
Also, not sure if it is related, but after having the site open for a few minutes, I get a `Search Error - An unhandled error occurred`
![image](https://github.com/Olog/phoebus-olog-web-client/assets/43409317/b3fcf836-cff4-4200-a7f6-adf94cb83fe3)

Any help would be appreciated,
Urban

**Comment by UrbanBobek** [comment]
Hi all,

after a bit of testing I found the issues. The instructions in the README say to specify `REACT_APP_BASE_URL` as `Olog/` when building the app and setting the proxy pass to `/Olog/` in the apache config file.

The issue I described is caused because the client sends incorrect requests which is caused by the omission of the `/` symbol in the `REACT_APP_BASE_URL` variable.

So, the command I used to build the app was:
```
REACT_APP_BASE_URL=/Olog/ npm run-script build
```
which, using the configuration I provided, fixed the issue.

PS: the command in the README contains the `>` symbol, which causes command to fail.

**Comment by cjenkscybercom** [comment]
Hi,

We can remove ">" from the docs so copy-paste folks don't make that mistake. I'll include some improvements in https://github.com/Olog/phoebus-olog-web-client/pull/119 however if you have better suggestions you are of course welcome to contribute.

Otherwise this makes sense since `Olog/` is a relative url whereas `/Olog/` is absolute, as the examples assume you provide an absolute url (with the host, port, etc) rather than relative one.
