### ISSUE TITLE
Level field in customization.js is not used

### ISSUE THREAD

**Issue by UrbanBobek** [Olog/phoebus-olog-web-client#103]
Hi all,

Before building the app I edited the values of `levelValues`, `defaultLevel` and `level` fields in the `customization.js` file.
After deploying the app, the values of `levelValues` and `defaultLevel` were successfully updated, but the value of `level` remained the same (`Entry Type`). 

After digging around the source code I found that in the `EntryEditor.js` file, `Entry Type` is hard-coded as the level label value.

A fix is to change the hard-coded label with the call to `customization.level` on the following line
https://github.com/Olog/phoebus-olog-web-client/blob/40765193caf2774b91b44edc510fdc027ebd4fc5/src/components/EntryEditor/EntryEditor.js#L476C47-L476C47

So replace 
```
label='Entry Type' 
```
with 
```
label={customization.level}
```

Best regards,

Urban

**Comment by cjenkscybercom** [comment]
Huh, didn't notice/expect that'd be customizable! 
Usually it's all (having internationalization keys) or nothing (hardcoded like it 99% is currently) so I'm curious about the use case here? Thanks!

(I'll put it back to where it was in https://github.com/Olog/phoebus-olog-web-client/pull/119, would just like to understand this better)
