### ISSUE TITLE
Log editing issues

### ISSUE THREAD

**Issue by echandler-anl** [Olog/phoebus-olog-web-client#117]
I'm using the latest code of Olog web client with the new editing feature.   If I try to edit an existing log, it seems to strip some of the markdown. For example if I create a new log with a header
```
# header
```

And then hit the "edit" button, the text will look like
```
header
```

It also strips the `()` around embedded images.

A second issue I found with editing is that after editing the log and hit "Submit" and it goes back to the main page, it doesn't show the new changes.  I need to refresh the page in order to see the changes.

PS:  We're excited to use the new editing feature!

**Comment by cjenkscybercom** [comment]
Ah, I see what is happening! I'll include this in https://github.com/Olog/phoebus-olog-web-client/pull/119
