### ISSUE TITLE
Reply only works with attachment. 

### ISSUE THREAD

**Issue by iTerminate** [Olog/phoebus-olog-web-client#121]
Whenever I try to reply to a log without an attachment I get the error: "Attachments exceed total maximum upload size of 100MB". If I attach a file I can reply to a log.

**Comment by cjenkscybercom** [comment]
This is as expected, the edit feature does not support attachments at the moment.

**Comment by iTerminate** [comment]
@cjenkscybercom this is not about the edit feature. I cannot reply to a log unless I have added an attachment. If there is no attachment it stops me with the warning that I exceeded total max upload size even though there are no attachments.
