### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by GDH-ISIS** [Olog/phoebus-olog-web-client#127]
May I please ask for some advice relating to networking/connecting the services together. I have a phoebus olog service running on a linux cluster, configured and connected to phoebus running on Windows. We were interested in also using the phoebus olog web client for flexibility. Having configured a dockerfile and docker-compose file, I am having odd problems connecting the phoebus olog web client to the phoebus olog service, which I believe might be network related.
Details are :
http://localhost:3000 - Everything works, phoebus olog reports are displayed on web page as one would expect - my compliments.
http://127.0.0.1:3000 - Message on the web page reporting "Search Error. Could not reach the logbook service"
http://ip-address:3000 - Message on the web page reporting "Search Error. Could not reach the logbook service"
http://machine-name:3000 - Message on the web page reporting "Search Error. Could not reach the logbook service"
I am using Docker to configure the services, have tried on both Linux and Windows. Docker service is not restarted during test. Trying localhost again, works.
Any advice on where to look much appreciated.

**Comment by cjenkscybercom** [comment]
The client assumes the backend and frontend are on the same host currently. 

You can configure the host/base url for the frontend  via`REACT_APP_BASE_URL`, however note that it is a compile/build-time dependency (you must provide it when building the project, not after it has been built and deployed).

**Comment by GDH-ISIS** [comment]
Thank you for the reply - the hint regarding REACT_APP_BASE_URL was very useful. Our control system is being developed using docker containers, hence our interest in running the phoebus-olog-web-client as a stand alone container. After some initial investigations, it does look as though it is possible to run the phoebus-olog and phoebus-olog-web-client as two separate docker containers - finding the settings took a while which did indeed involve setting the cross-origin request (cors.allowed.origins) in the .properties file. Many thanks.
