### ISSUE TITLE
Enabling https for phoebus-olog-web-client

### ISSUE THREAD

**Issue by GDH-ISIS** [Olog/phoebus-olog-web-client#131]
Please excuse my lack of knowledge, but I am interested in enabling https for the phoebus-olog-web-client service, particularly as users can sign in. Not being an npm developer, are there any instructions available for enabling https.

**Comment by cjenkscybercom** [comment]
The REACT_APP_BASE_URL is where you would specify the backend url (https://your-backend.domain).

Beyond that, it will depend entirely on how you deploy the frontend; this is purely an infrastructure/deployment concern. If you need help with that, then you need to discuss this with whoever manages your deployment, and/or seek help from web sources or possibly an AI like ChatGPT.
