### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by konrad-gajewski** [Olog/phoebus-olog-web-client#133]
I've tried to deploy olog web client on apache server but the requests to Olog back-end are blocked on my browser (Firefox). The web client works ok when running in test mode on http://localhost:3000.
I've followed the description in README in this repository. URL of my olog server is http://192.168.10.118:8080/Olog/
The apache configuration file looks like below:

```
VirtualHost *:80>
   ProxyPreserveHost On
   ServerName test-1.freia.local
   ProxyPass /Olog/ http://192.168.10.118:8080/Olog/
   ProxyPassReverse /Olog/ http://192.168.10.118:8080/Olog/

   <Directory "/var/www/html">
      RewriteEngine on
      RewriteCond %{HTTP_ACCEPT} text/html
      RewriteCond %{REQUEST_FILENAME} !-f
      RewriteRule ^ index.html [last]
      RewriteRule ^ - [last]
   </Directory>
</VirtualHost>
```

After opening http://test-1.freia.local I get the start page of olog web client and a pop-up: 
"Search Error Could not reach the logbook service". 
In the web browser's console window I can see the following messages:
An error occurred while fetching search results 
Object { status: "FETCH_ERROR", error: "TypeError: NetworkError when attempting to fetch resource." }
main.614938bd.js:2:1325397
    oU http://192.168.10.154/static/js/main.614938bd.js:2
    ki http://192.168.10.154/static/js/main.614938bd.js:2
    Ml http://192.168.10.154/static/js/main.614938bd.js:2
    ks http://192.168.10.154/static/js/main.614938bd.js:2
    wc http://192.168.10.154/static/js/main.614938bd.js:2
    bc http://192.168.10.154/static/js/main.614938bd.js:2
    vc http://192.168.10.154/static/js/main.614938bd.js:2
    cc http://192.168.10.154/static/js/main.614938bd.js:2
    Bo http://192.168.10.154/static/js/main.614938bd.js:2
    oc http://192.168.10.154/static/js/main.614938bd.js:2
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://192.168.10.118:8080/Olog/logs/search?start=172+hours&end=now&sort=down&from=0&size=30. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 403.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://192.168.10.118:8080/Olog/logs/search?start=172+hours&end=now&sort=down&from=0&size=30. (Reason: CORS request did not succeed). Status code: (null).

I have tried to add the statement:
`   Header set Access-Control-Allow-Origin "*"
`
in the Directory section but it didn't help. I'm not a web server expert and I'm probably missing something in the configuration. Any help will be much appreciated.

**Comment by cjenkscybercom** [comment]
Sorry,

This isn't something we can help with. 

I did double check for you that the redux-rtk fetchBaseQuery configuration in `src/ologApi.js` is using the default settings (with cors enabled). So, this would be an issue with your deployment environment.

I would recommend taking a look at a guide such as https://www.stackhawk.com/blog/react-cors-guide-what-it-is-and-how-to-enable-it/#cors-should-always-be-handled-from-server-side or take this to your internal deployment colleagues/team. Also be aware the backend https://github.com/Olog/phoebus-olog does have CORS header settings that you should be setting as well to allow the FE's origin.

**Comment by konrad-gajewski** [comment]
@cjenkscybercom, thanks for pointing out the need of setting cors.allowed.origins property to allow FE's origin. After adding http:<my-web-olog-client> (without any port number) I've got the connection. However, I encountered a problem in log entries with the attachments - phoebus-olog BE rejected requests having "//" in the URL. Removing the trailing slash in REACT_APP_BASE_URL definition when building the static pages as described in Deployment section in point 2. 
It would be nice (and hopefully help other non web experts like me) if you could update the line
`REACT_APP_BASE_URL=Olog/ npm run-script build`
with 
`REACT_APP_BASE_URL=http:<olog-server>:8080/Olog`

I think that for the encrypted connection it should look like below but I haven't tested it:
`REACT_APP_BASE_URL=https:<olog-server>:8181/Olog`

**Comment by cjenkscybercom** [comment]
Sure! 
I can clarify that variable's value in the updated README since the BE url is a little strange in how it has that extra context path in the base url.
