### ISSUE TITLE
Installing and running olog-web-client in other directory than root

### ISSUE THREAD

**Issue by konrad-gajewski** [Olog/phoebus-olog-web-client#136]
Sorry to bother you again. I understand that it's more a deployment issue than the web application issue but I have tried a lot of options that I could found on the web and failed. 
I would like to know if it's possible at all to get it work in the set-up with olog BE not on the same computer as olog-web-client. Would it be easier if they would be on the same computer?
I have defined `"homepage": "http://192.168.10.154/olog",`in package.json as described on https://create-react-app.dev/docs/deployment tried different definitions of PUBLIC_URL as on https://create-react-app.dev/docs/deployment but every time I open http://192.168.10.154/olog i get an empty page or en error: "Unexpected Application Error! 404 Not Found"

**Comment by cjenkscybercom** [comment]
Oh! In that case /olog on the frontend is an unknown page so the 404 is correct. 
You should be able to access everything from /, e.g. if you run it locally at http://localhost:3000 or http://localhost:3000/
Also, the BE serves the api from /Olog, not /olog

**Comment by konrad-gajewski** [comment]
This is an misunderstanding. This olog after the address of my FE can be anything and has nothing to do with Olog on the BE. My idea was to use our existing web server as a FE and put your software not in a DocumentRoot of this server but under some sub-directory (e.i. olog-web-client), so it can be accessed via https://my.server/olog-web-client.

**Comment by cjenkscybercom** [comment]
Ohhhhh! Okay thank you for your patience in clarifying. 
I think that may be a routing issue on the FE in that case...I'll investigate. We use react-router v6 but we don't currently set the basename to anything other than the default.

**Comment by cjenkscybercom** [comment]
Okay, thought I'd like you know that yes it is a routing related problem. 
I've got other higher priority work in my own backlog at the moment so it may be a while until I can get to this, if you need this sooner then you may consider forking or contributing yourself.

**Comment by konrad-gajewski** [comment]
Thank you, I will try to make a route rewriting on my web server as you suggested. I'd be happy to contribute to the project but considering my current knowledge in this area it would' require a considerable effort from my side which I can't afford now.

**Comment by cjenkscybercom** [comment]
Okay, we've discussed this internally and don't feel the value this provides would be worth the complexity this would introduce. So, we're going to close this request, thanks for your patience!
