### ISSUE TITLE
Issue with multiple attachments with same name in a single log entry.

### ISSUE THREAD

**Issue by imranau** [Olog/phoebus-olog-web-client#51]
When a log entry or reply is created with multiple attachments images with same name, the log entry's single view on home page gets corrupted. The attachment section of log entry is unable to show those images. And the API https://<host>/Olog/logs/attachments/<entry id>/<attachment name> is unable to fetch the attachment.
 
To reproduce:
1. Click on new log entry.
2. Embed an image with name image.png to you log entry text. Then embed another image with name image.png after new line.
3. Click in this entry on home page and see attachments section. It appears corrupted.
4. Click on the attachments in attachments section, it won't open or download.
5. API https://<host>/Olog/attachment/<attachment id> still works, so I don't think there is a backend issue.

I think the API https://<host>/Olog/logs/attachments/<entry id>/<attachment name> should not be used at all. Since there will always be a clash if there are multiple attachments with same name. Instead https://<host>/Olog/attachment/<attachment id> should be used.

**Comment by cjenkscybercom** [comment]
We're having trouble reproducing this problem, do you also see this with the Phoebus/Java client? (we cannot reproduce it there either)
