### ISSUE TITLE
Add a feature to temporary save a log entry as a draft.

### ISSUE THREAD

**Issue by imranau** [Olog/phoebus-olog-web-client#56]
Add a feature to temporary save a log entry as a draft. With this feature:
1. User can click on Draft button and create and save a new log entry as draft.
2. User can retrieve the same draft entry again in future by clicking the Draft button again and continue to edit it.
3. Once user thinks the draft entry is complete, they can click submit to save it permanently.
4. This means a single user can have at most one draft entry, which will appear on clicking Draft button.
5. The draft page would be different from New Log Entry page. So the user will still be able to create new log entries while saving one as a draft.

**Comment by cjenkscybercom** [comment]
This feature is now incorporated into main/master via b23f69213bef3882e7dc1c8f735e25a5c7fd7be1
