### ISSUE TITLE
Clicking on 'New Log Entry' button on home page creates a reply to the currently selected entry.

### ISSUE THREAD

**Issue by imranau** [Olog/phoebus-olog-web-client#7]
To reproduce this bug:
1. Select an entry from the search results list to view its entry log and metadata.
2. Click on 'New Log Entry' button on the top left and create a new log entry.
3. The newly created log entry appears as a reply to the entry which was select when you clicked 'New Log Entry' button.

The 'New Log Entry' button should create an independent new entry, not a reply to another entry.

**Comment by georgweiss** [comment]
This should be fixed in latest code. Please verify.

**Comment by georgweiss** [comment]
@imranau, can you verify that this is fixed?

**Comment by imranau** [comment]
This issue is fixed. Thanks.
