### ISSUE TITLE
Search using 'Created from - to' filter is not working as expected

### ISSUE THREAD

**Issue by imranau** [Olog/phoebus-olog-web-client#8]
To reproduce this issue:
1. Create a new entry using 'New Log Entry' button.
2. From the search filters use  'Created from - to' filter to select 'From' date as yesterday's date and 'To' date as today's date with current time(not 'now' string).
3. Click on search button.

The search results should have the entry you recently created but it doesn't.

**Comment by georgweiss** [comment]
Admit that filter view is incomplete and probably has several issues. I'm thinking of removing it until we have the time to fix it. Feel free to contribute to that, but currently I need to prioritize other tasks.

**Comment by georgweiss** [comment]
Pushed a commit that disables the filters view. I'd prefer not to show it until we can offer the expected behavior.

Also fixed the search string input field. User may always type the search parameters explicitly, e.g. 

``start=12 hours&end=now``

**Comment by imranau** [comment]
Do you know if this issue is a server side issue or a client side issue?
I mean if phoebus-olog server is sending wrong search results or phoebus-olog-web-client's filter view is sending/generating wrong search parameters?

**Comment by georgweiss** [comment]
The filter implementation - currently commented out - is client side. The server API expects the client to construct a query using the supported date format, which is yyyy-MM-dd HH:mm:ss.SSS.

**Comment by imranau** [comment]
I have created a new pull request with branch name filter-date. That should fix this issue.
